<?php

namespace MB\Bitrix\EntityView\Parameters;

use Bitrix\Main\ORM\Entity as ORMEntity;

class Filter extends Base
{
    protected ORMEntity $entity;

    /**
     * @param ORMEntity $entity
     */
    public function __construct(ORMEntity $entity)
    {
        $this->entity = $entity;
        parent::__construct();
    }

    protected function getDefault(): array
    {
        return parent::getDefault(); // TODO: Change the autogenerated stub
    }
}
